# Generated by Django 2.1.1 on 2018-10-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20181010_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='basic_app.SiteUser'),
        ),
    ]
