# Generated by Django 2.1.1 on 2018-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20181010_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='remark',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
