# Generated by Django 2.1.1 on 2018-10-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20181010_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Student'),
        ),
    ]
