# Generated by Django 2.1.1 on 2018-10-11 08:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_app.SiteUser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.PositiveIntegerField(blank=True, null=True)),
                ('science', models.PositiveIntegerField(blank=True, null=True)),
                ('english', models.PositiveIntegerField(blank=True, null=True)),
                ('tamil', models.PositiveIntegerField(blank=True, null=True)),
                ('evs', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.SiteUser')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.StudentMarks'),
        ),
    ]
